import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/auth-context";
import { AppWrapper } from "@/context/app-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
      <AppWrapper>
        <body
          className={`h-svh relative bg-slate-200 dark:bg-slate-800 ${inter.className}`}
        >
          <AuthProvider>{children}</AuthProvider>
        </body>
      </AppWrapper>
    </html>
  );
}
